"""cria tabela quadras

Revision ID: 5b023e5b277f
Revises: 83990f3ad1cd
Create Date: 2026-10-04 20:19:33.294790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b023e5b277f'
down_revision: Union[str, Sequence[str], None] = '83990f3ad1cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quadras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo_esporte', sa.String(length=20), nullable=False),
    sa.Column('piso', sa.String(length=60), nullable=False),
    sa.Column('comprimento_m', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('largura_m', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('preco_hora', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('coberta', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('iluminacao', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('replay', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('vestiario', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ativa', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tipo_esporte IN ('futebol', 'futsal', 'tenis', 'volei', 'basquete')", name='ck_quadras_tipo_esporte'),
    sa.CheckConstraint('comprimento_m > 0 AND largura_m > 0', name='ck_quadras_dimensoes'),
    sa.CheckConstraint('preco_hora > 0', name='ck_quadras_preco_hora'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', name='uq_quadras_nome')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quadras')
    # ### end Alembic commands ###
