"""cria tabela usuarios

Revision ID: 83990f3ad1cd
Revises: 
Create Date: 2026-10-04 04:38:09.219457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83990f3ad1cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('telefone', sa.String(length=11), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.String(length=20), server_default='usuario', nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("perfil IN ('usuario', 'administrador')", name='ck_usuarios_perfil'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf', name='uq_usuarios_cpf'),
    sa.UniqueConstraint('email', name='uq_usuarios_email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    # ### end Alembic commands ###
