"""adiciona horario de funcionamento das quadras

Revision ID: 8e049c622817
Revises: 17455edafc3c
Create Date: 2026-10-04 23:17:07.970327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e049c622817'
down_revision: Union[str, Sequence[str], None] = '17455edafc3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quadras', sa.Column('hora_abertura', sa.SmallInteger(), server_default=sa.text('8'), nullable=False))
    op.add_column('quadras', sa.Column('hora_fechamento', sa.SmallInteger(), server_default=sa.text('22'), nullable=False))
    # ### end Alembic commands ###
    op.create_check_constraint(
        "ck_quadras_horario",
        "quadras",
        "hora_abertura >= 0 AND hora_fechamento <= 24 "
        "AND hora_abertura < hora_fechamento",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("ck_quadras_horario", "quadras", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quadras', 'hora_fechamento')
    op.drop_column('quadras', 'hora_abertura')
    # ### end Alembic commands ###
