"""cria tabela reservas

Revision ID: 9421f8449138
Revises: 8e049c622817
Create Date: 2026-10-04 23:21:51.883589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9421f8449138'
down_revision: Union[str, Sequence[str], None] = '8e049c622817'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('quadra_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('horario', sa.SmallInteger(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pendente', nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pendente', 'paga', 'cancelada')", name='ck_reservas_status'),
    sa.CheckConstraint('horario >= 0 AND horario <= 23', name='ck_reservas_horario'),
    sa.CheckConstraint('valor > 0', name='ck_reservas_valor'),
    sa.ForeignKeyConstraint(['quadra_id'], ['quadras.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservas_usuario_id'), 'reservas', ['usuario_id'], unique=False)
    op.create_index('uq_reservas_quadra_data_horario', 'reservas', ['quadra_id', 'data', 'horario'], unique=True, postgresql_where=sa.text("status <> 'cancelada'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_reservas_quadra_data_horario', table_name='reservas', postgresql_where=sa.text("status <> 'cancelada'"))
    op.drop_index(op.f('ix_reservas_usuario_id'), table_name='reservas')
    op.drop_table('reservas')
    # ### end Alembic commands ###
